import Foundation

struct RGB {
    var red: Double
    var green: Double
    var blue: Double
}

struct Preset {
    let filename: String
    let title: String
    let transform: (RGB) -> RGB
}

let cubeSize = 17
let outputDirectory = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
    .appending(path: "Lutty/Resources/BundledLUTs", directoryHint: .isDirectory)

func clamp(_ value: Double) -> Double {
    min(max(value, 0), 1)
}

func luminance(_ color: RGB) -> Double {
    color.red * 0.2126 + color.green * 0.7152 + color.blue * 0.0722
}

func tone(_ value: Double, contrast: Double, lift: Double, gamma: Double) -> Double {
    let adjusted = pow(clamp(value), gamma)
    return clamp(lift + (1 - lift) * ((adjusted - 0.5) * contrast + 0.5))
}

func saturation(_ color: RGB, amount: Double) -> RGB {
    let gray = luminance(color)
    return RGB(
        red: gray + (color.red - gray) * amount,
        green: gray + (color.green - gray) * amount,
        blue: gray + (color.blue - gray) * amount
    )
}

let presets = [
    Preset(filename: "Soft-Warm.cube", title: "Soft Warm") { input in
        let base = RGB(
            red: tone(input.red, contrast: 0.96, lift: 0.012, gamma: 0.98),
            green: tone(input.green, contrast: 0.96, lift: 0.012, gamma: 0.99),
            blue: tone(input.blue, contrast: 0.96, lift: 0.012, gamma: 1.01)
        )
        let light = luminance(base)
        return RGB(
            red: clamp(base.red + 0.022 * light + 0.004),
            green: clamp(base.green + 0.006 * light),
            blue: clamp(base.blue - 0.018 * light)
        )
    },
    Preset(filename: "Golden-Hour.cube", title: "Golden Hour") { input in
        let base = saturation(input, amount: 1.03)
        let light = luminance(base)
        return RGB(
            red: clamp(tone(base.red, contrast: 1.01, lift: 0.006, gamma: 0.97) + 0.052 * light),
            green: clamp(tone(base.green, contrast: 1.0, lift: 0.006, gamma: 0.99) + 0.016 * light),
            blue: clamp(tone(base.blue, contrast: 0.99, lift: 0.008, gamma: 1.03) - 0.038 * light)
        )
    },
    Preset(filename: "Rose-Fade.cube", title: "Rose Fade") { input in
        let base = saturation(input, amount: 0.94)
        let light = luminance(base)
        let shadow = 1 - light
        return RGB(
            red: clamp(tone(base.red, contrast: 0.92, lift: 0.024, gamma: 0.99) + 0.022 * light),
            green: clamp(tone(base.green, contrast: 0.93, lift: 0.016, gamma: 1.01) - 0.006 * light),
            blue: clamp(tone(base.blue, contrast: 0.92, lift: 0.022, gamma: 1.0) + 0.010 * shadow)
        )
    },
    Preset(filename: "Story-Glow.cube", title: "Story Glow") { input in
        let base = saturation(input, amount: 1.045)
        let light = luminance(base)
        return RGB(
            red: clamp(tone(base.red, contrast: 0.97, lift: 0.014, gamma: 0.94) + 0.018 * light),
            green: clamp(tone(base.green, contrast: 0.97, lift: 0.014, gamma: 0.96) + 0.006 * light),
            blue: clamp(tone(base.blue, contrast: 0.96, lift: 0.016, gamma: 0.99) - 0.012 * light)
        )
    }
]

try FileManager.default.createDirectory(at: outputDirectory, withIntermediateDirectories: true)

for preset in presets {
    var lines = [
        "# Generated by Scripts/generate_bundled_luts.swift",
        "TITLE \"\(preset.title)\"",
        "LUT_3D_SIZE \(cubeSize)",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
        ""
    ]

    for blueIndex in 0..<cubeSize {
        for greenIndex in 0..<cubeSize {
            for redIndex in 0..<cubeSize {
                let denominator = Double(cubeSize - 1)
                let input = RGB(
                    red: Double(redIndex) / denominator,
                    green: Double(greenIndex) / denominator,
                    blue: Double(blueIndex) / denominator
                )
                let output = preset.transform(input)
                lines.append(String(
                    format: "%.6f %.6f %.6f",
                    locale: Locale(identifier: "en_US_POSIX"),
                    clamp(output.red),
                    clamp(output.green),
                    clamp(output.blue)
                ))
            }
        }
    }

    let destination = outputDirectory.appending(path: preset.filename)
    try (lines.joined(separator: "\n") + "\n").write(to: destination, atomically: true, encoding: .utf8)
}
